service: SLS-testSNSlistener

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 30
  stage: dev1
  region: us-east-1

functions:
  listener:
    handler: lambdas/listener.handler
    description: Lambda that listens to APIG endpoing subscribed to SNS topic
    events:
      - http:
          path: snsWebhook
          method: post
          cors: true
